services:
  - type: web
    name: django-delights
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangodelights.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-delights
          property: connectionString