services:
  - type: web
    name: django-delights
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      echo "Applying migrations..." && \
      python manage.py migrate --noinput || { echo 'Migrations failed'; exit 1; } && \
      echo "Starting Gunicorn..." && \
      gunicorn djangodelights.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
