services:
  - type: web
    name: django-delights
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn djangodelights.wsgi:application
