services:
  - type: web
    name: django-delights
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangodelights.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    postdeploy: |
      python manage.py migrate
