# Generated by Django 5.1 on 2024-08-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delights.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_ingredient_name'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('menuitem',), name='unique_menuitem'),
        ),
        migrations.AddConstraint(
            model_name='reciperequirement',
            constraint=models.UniqueConstraint(fields=('ingredients', 'menuitem'), name='unique_recipe_requirement'),
        ),
    ]
